using System;
using System.Collections.Generic;

namespace API.Models
{
    public partial class DaneExtDef
    {
        public int IdDaneExtDef { get; set; }
        public int ObiektTyp { get; set; }
        public int FrmId { get; set; }
        public string Tekst1Lbl { get; set; }
        public int? Tekst1Act { get; set; }
        public int? Tekst1Req { get; set; }
        public int? Tekst1Lp { get; set; }
        public string Data1Lbl { get; set; }
        public int? Data1Act { get; set; }
        public int? Data1Req { get; set; }
        public int? Data1Lp { get; set; }
        public string Liczba1Lbl { get; set; }
        public int? Liczba1Act { get; set; }
        public int? Liczba1Req { get; set; }
        public int? Liczba1Lp { get; set; }
        public string Bit1Lbl { get; set; }
        public int? Bit1Act { get; set; }
        public int? Bit1Req { get; set; }
        public int? Bit1Lp { get; set; }
        public string Tekst2Lbl { get; set; }
        public int? Tekst2Act { get; set; }
        public int? Tekst2Req { get; set; }
        public int? Tekst2Lp { get; set; }
        public string Data2Lbl { get; set; }
        public int? Data2Act { get; set; }
        public int? Data2Req { get; set; }
        public int? Data2Lp { get; set; }
        public string Liczba2Lbl { get; set; }
        public int? Liczba2Act { get; set; }
        public int? Liczba2Req { get; set; }
        public int? Liczba2Lp { get; set; }
        public string Bit2Lbl { get; set; }
        public int? Bit2Act { get; set; }
        public int? Bit2Req { get; set; }
        public int? Bit2Lp { get; set; }
        public string Tekst3Lbl { get; set; }
        public int? Tekst3Act { get; set; }
        public int? Tekst3Req { get; set; }
        public int? Tekst3Lp { get; set; }
        public string Data3Lbl { get; set; }
        public int? Data3Act { get; set; }
        public int? Data3Req { get; set; }
        public int? Data3Lp { get; set; }
        public string Liczba3Lbl { get; set; }
        public int? Liczba3Act { get; set; }
        public int? Liczba3Req { get; set; }
        public int? Liczba3Lp { get; set; }
        public string Bit3Lbl { get; set; }
        public int? Bit3Act { get; set; }
        public int? Bit3Req { get; set; }
        public int? Bit3Lp { get; set; }
        public string Tekst4Lbl { get; set; }
        public int? Tekst4Act { get; set; }
        public int? Tekst4Req { get; set; }
        public int? Tekst4Lp { get; set; }
        public string Data4Lbl { get; set; }
        public int? Data4Act { get; set; }
        public int? Data4Req { get; set; }
        public int? Data4Lp { get; set; }
        public string Liczba4Lbl { get; set; }
        public int? Liczba4Act { get; set; }
        public int? Liczba4Req { get; set; }
        public int? Liczba4Lp { get; set; }
        public string Bit4Lbl { get; set; }
        public int? Bit4Act { get; set; }
        public int? Bit4Req { get; set; }
        public int? Bit4Lp { get; set; }
        public string Tekst5Lbl { get; set; }
        public int? Tekst5Act { get; set; }
        public int? Tekst5Req { get; set; }
        public int? Tekst5Lp { get; set; }
        public string Data5Lbl { get; set; }
        public int? Data5Act { get; set; }
        public int? Data5Req { get; set; }
        public int? Data5Lp { get; set; }
        public string Liczba5Lbl { get; set; }
        public int? Liczba5Act { get; set; }
        public int? Liczba5Req { get; set; }
        public int? Liczba5Lp { get; set; }
        public string Bit5Lbl { get; set; }
        public int? Bit5Act { get; set; }
        public int? Bit5Req { get; set; }
        public int? Bit5Lp { get; set; }
        public string Tekst6Lbl { get; set; }
        public int? Tekst6Act { get; set; }
        public int? Tekst6Req { get; set; }
        public int? Tekst6Lp { get; set; }
        public string Data6Lbl { get; set; }
        public int? Data6Act { get; set; }
        public int? Data6Req { get; set; }
        public int? Data6Lp { get; set; }
        public string Liczba6Lbl { get; set; }
        public int? Liczba6Act { get; set; }
        public int? Liczba6Req { get; set; }
        public int? Liczba6Lp { get; set; }
        public string Bit6Lbl { get; set; }
        public int? Bit6Act { get; set; }
        public int? Bit6Req { get; set; }
        public int? Bit6Lp { get; set; }
        public string Tekst7Lbl { get; set; }
        public int? Tekst7Act { get; set; }
        public int? Tekst7Req { get; set; }
        public int? Tekst7Lp { get; set; }
        public string Data7Lbl { get; set; }
        public int? Data7Act { get; set; }
        public int? Data7Req { get; set; }
        public int? Data7Lp { get; set; }
        public string Liczba7Lbl { get; set; }
        public int? Liczba7Act { get; set; }
        public int? Liczba7Req { get; set; }
        public int? Liczba7Lp { get; set; }
        public string Bit7Lbl { get; set; }
        public int? Bit7Act { get; set; }
        public int? Bit7Req { get; set; }
        public int? Bit7Lp { get; set; }
        public string Tekst8Lbl { get; set; }
        public int? Tekst8Act { get; set; }
        public int? Tekst8Req { get; set; }
        public int? Tekst8Lp { get; set; }
        public string Data8Lbl { get; set; }
        public int? Data8Act { get; set; }
        public int? Data8Req { get; set; }
        public int? Data8Lp { get; set; }
        public string Liczba8Lbl { get; set; }
        public int? Liczba8Act { get; set; }
        public int? Liczba8Req { get; set; }
        public int? Liczba8Lp { get; set; }
        public string Bit8Lbl { get; set; }
        public int? Bit8Act { get; set; }
        public int? Bit8Req { get; set; }
        public int? Bit8Lp { get; set; }
        public string Tekst9Lbl { get; set; }
        public int? Tekst9Act { get; set; }
        public int? Tekst9Req { get; set; }
        public int? Tekst9Lp { get; set; }
        public string Data9Lbl { get; set; }
        public int? Data9Act { get; set; }
        public int? Data9Req { get; set; }
        public int? Data9Lp { get; set; }
        public string Liczba9Lbl { get; set; }
        public int? Liczba9Act { get; set; }
        public int? Liczba9Req { get; set; }
        public int? Liczba9Lp { get; set; }
        public string Bit9Lbl { get; set; }
        public int? Bit9Act { get; set; }
        public int? Bit9Req { get; set; }
        public int? Bit9Lp { get; set; }
        public string Tekst10Lbl { get; set; }
        public int? Tekst10Act { get; set; }
        public int? Tekst10Req { get; set; }
        public int? Tekst10Lp { get; set; }
        public string Data10Lbl { get; set; }
        public int? Data10Act { get; set; }
        public int? Data10Req { get; set; }
        public int? Data10Lp { get; set; }
        public string Liczba10Lbl { get; set; }
        public int? Liczba10Act { get; set; }
        public int? Liczba10Req { get; set; }
        public int? Liczba10Lp { get; set; }
        public string Bit10Lbl { get; set; }
        public int? Bit10Act { get; set; }
        public int? Bit10Req { get; set; }
        public int? Bit10Lp { get; set; }
        public int? Tekst1List { get; set; }
        public int? Tekst2List { get; set; }
        public int? Tekst3List { get; set; }
        public int? Tekst4List { get; set; }
        public int? Tekst5List { get; set; }
        public int? Tekst6List { get; set; }
        public int? Tekst7List { get; set; }
        public int? Tekst8List { get; set; }
        public int? Tekst9List { get; set; }
        public int? Tekst10List { get; set; }
        public string Tekst11Lbl { get; set; }
        public int? Tekst11Act { get; set; }
        public int? Tekst11Req { get; set; }
        public int? Tekst11Lp { get; set; }
        public int? Tekst11List { get; set; }
        public string Data11Lbl { get; set; }
        public int? Data11Act { get; set; }
        public int? Data11Req { get; set; }
        public int? Data11Lp { get; set; }
        public string Liczba11Lbl { get; set; }
        public int? Liczba11Act { get; set; }
        public int? Liczba11Req { get; set; }
        public int? Liczba11Lp { get; set; }
        public string Bit11Lbl { get; set; }
        public int? Bit11Act { get; set; }
        public int? Bit11Req { get; set; }
        public int? Bit11Lp { get; set; }
        public string Tekst12Lbl { get; set; }
        public int? Tekst12Act { get; set; }
        public int? Tekst12Req { get; set; }
        public int? Tekst12Lp { get; set; }
        public int? Tekst12List { get; set; }
        public string Data12Lbl { get; set; }
        public int? Data12Act { get; set; }
        public int? Data12Req { get; set; }
        public int? Data12Lp { get; set; }
        public string Liczba12Lbl { get; set; }
        public int? Liczba12Act { get; set; }
        public int? Liczba12Req { get; set; }
        public int? Liczba12Lp { get; set; }
        public string Bit12Lbl { get; set; }
        public int? Bit12Act { get; set; }
        public int? Bit12Req { get; set; }
        public int? Bit12Lp { get; set; }
        public string Tekst13Lbl { get; set; }
        public int? Tekst13Act { get; set; }
        public int? Tekst13Req { get; set; }
        public int? Tekst13Lp { get; set; }
        public int? Tekst13List { get; set; }
        public string Data13Lbl { get; set; }
        public int? Data13Act { get; set; }
        public int? Data13Req { get; set; }
        public int? Data13Lp { get; set; }
        public string Liczba13Lbl { get; set; }
        public int? Liczba13Act { get; set; }
        public int? Liczba13Req { get; set; }
        public int? Liczba13Lp { get; set; }
        public string Bit13Lbl { get; set; }
        public int? Bit13Act { get; set; }
        public int? Bit13Req { get; set; }
        public int? Bit13Lp { get; set; }
        public string Tekst14Lbl { get; set; }
        public int? Tekst14Act { get; set; }
        public int? Tekst14Req { get; set; }
        public int? Tekst14Lp { get; set; }
        public int? Tekst14List { get; set; }
        public string Data14Lbl { get; set; }
        public int? Data14Act { get; set; }
        public int? Data14Req { get; set; }
        public int? Data14Lp { get; set; }
        public string Liczba14Lbl { get; set; }
        public int? Liczba14Act { get; set; }
        public int? Liczba14Req { get; set; }
        public int? Liczba14Lp { get; set; }
        public string Bit14Lbl { get; set; }
        public int? Bit14Act { get; set; }
        public int? Bit14Req { get; set; }
        public int? Bit14Lp { get; set; }
        public string Tekst15Lbl { get; set; }
        public int? Tekst15Act { get; set; }
        public int? Tekst15Req { get; set; }
        public int? Tekst15Lp { get; set; }
        public int? Tekst15List { get; set; }
        public string Data15Lbl { get; set; }
        public int? Data15Act { get; set; }
        public int? Data15Req { get; set; }
        public int? Data15Lp { get; set; }
        public string Liczba15Lbl { get; set; }
        public int? Liczba15Act { get; set; }
        public int? Liczba15Req { get; set; }
        public int? Liczba15Lp { get; set; }
        public string Bit15Lbl { get; set; }
        public int? Bit15Act { get; set; }
        public int? Bit15Req { get; set; }
        public int? Bit15Lp { get; set; }
        public string Tekst16Lbl { get; set; }
        public int? Tekst16Act { get; set; }
        public int? Tekst16Req { get; set; }
        public int? Tekst16Lp { get; set; }
        public int? Tekst16List { get; set; }
        public string Data16Lbl { get; set; }
        public int? Data16Act { get; set; }
        public int? Data16Req { get; set; }
        public int? Data16Lp { get; set; }
        public string Liczba16Lbl { get; set; }
        public int? Liczba16Act { get; set; }
        public int? Liczba16Req { get; set; }
        public int? Liczba16Lp { get; set; }
        public string Bit16Lbl { get; set; }
        public int? Bit16Act { get; set; }
        public int? Bit16Req { get; set; }
        public int? Bit16Lp { get; set; }
        public string Tekst17Lbl { get; set; }
        public int? Tekst17Act { get; set; }
        public int? Tekst17Req { get; set; }
        public int? Tekst17Lp { get; set; }
        public int? Tekst17List { get; set; }
        public string Data17Lbl { get; set; }
        public int? Data17Act { get; set; }
        public int? Data17Req { get; set; }
        public int? Data17Lp { get; set; }
        public string Liczba17Lbl { get; set; }
        public int? Liczba17Act { get; set; }
        public int? Liczba17Req { get; set; }
        public int? Liczba17Lp { get; set; }
        public string Bit17Lbl { get; set; }
        public int? Bit17Act { get; set; }
        public int? Bit17Req { get; set; }
        public int? Bit17Lp { get; set; }
        public string Tekst18Lbl { get; set; }
        public int? Tekst18Act { get; set; }
        public int? Tekst18Req { get; set; }
        public int? Tekst18Lp { get; set; }
        public int? Tekst18List { get; set; }
        public string Data18Lbl { get; set; }
        public int? Data18Act { get; set; }
        public int? Data18Req { get; set; }
        public int? Data18Lp { get; set; }
        public string Liczba18Lbl { get; set; }
        public int? Liczba18Act { get; set; }
        public int? Liczba18Req { get; set; }
        public int? Liczba18Lp { get; set; }
        public string Bit18Lbl { get; set; }
        public int? Bit18Act { get; set; }
        public int? Bit18Req { get; set; }
        public int? Bit18Lp { get; set; }
        public string Tekst19Lbl { get; set; }
        public int? Tekst19Act { get; set; }
        public int? Tekst19Req { get; set; }
        public int? Tekst19Lp { get; set; }
        public int? Tekst19List { get; set; }
        public string Data19Lbl { get; set; }
        public int? Data19Act { get; set; }
        public int? Data19Req { get; set; }
        public int? Data19Lp { get; set; }
        public string Liczba19Lbl { get; set; }
        public int? Liczba19Act { get; set; }
        public int? Liczba19Req { get; set; }
        public int? Liczba19Lp { get; set; }
        public string Bit19Lbl { get; set; }
        public int? Bit19Act { get; set; }
        public int? Bit19Req { get; set; }
        public int? Bit19Lp { get; set; }
        public string Tekst20Lbl { get; set; }
        public int? Tekst20Act { get; set; }
        public int? Tekst20Req { get; set; }
        public int? Tekst20Lp { get; set; }
        public int? Tekst20List { get; set; }
        public string Data20Lbl { get; set; }
        public int? Data20Act { get; set; }
        public int? Data20Req { get; set; }
        public int? Data20Lp { get; set; }
        public string Liczba20Lbl { get; set; }
        public int? Liczba20Act { get; set; }
        public int? Liczba20Req { get; set; }
        public int? Liczba20Lp { get; set; }
        public string Bit20Lbl { get; set; }
        public int? Bit20Act { get; set; }
        public int? Bit20Req { get; set; }
        public int? Bit20Lp { get; set; }
    }
}
