using System;
using System.Collections.Generic;

namespace API.Models
{
    public partial class Przesylki
    {
        public int IdPrzesylki { get; set; }
        public int? FrmId { get; set; }
        public string NrPrzesylki { get; set; }
        public string NrPrzesylkiEx { get; set; }
        public int? NrPrzesylkiKolejny { get; set; }
        public int? NrPrzesylkiRok { get; set; }
        public int? NrPrzesylkiMies { get; set; }
        public string NrBordero { get; set; }
        public DateTime? DataZlecenia { get; set; }
        public DateTime? PlanDataZal { get; set; }
        public DateTime? PlanGodzZal { get; set; }
        public DateTime? PlanDataRoz { get; set; }
        public DateTime? PlanGodzRoz { get; set; }
        public DateTime? FaktDataZal { get; set; }
        public DateTime? FaktGodzZal { get; set; }
        public DateTime? FaktDataRoz { get; set; }
        public DateTime? FaktGodzRoz { get; set; }
        public DateTime? DataDoreczenia { get; set; }
        public DateTime? GodzDoreczenia { get; set; }
        public DateTime? DataPodjecia { get; set; }
        public DateTime? GodzPodjecia { get; set; }
        public int? TeczkaId { get; set; }
        public string Teczka { get; set; }
        public int? KlientId { get; set; }
        public string KlientSymbol { get; set; }
        public string KlientNazwa { get; set; }
        public string KlientAdres { get; set; }
        public string KlientMiasto { get; set; }
        public string KlientKod { get; set; }
        public string KlientKraj { get; set; }
        public string KlientNip { get; set; }
        public int? PlatnikId { get; set; }
        public string PlatnikSymbol { get; set; }
        public string PlatnikNazwa { get; set; }
        public string PlatnikAdres { get; set; }
        public string PlatnikMiasto { get; set; }
        public string PlatnikKod { get; set; }
        public string PlatnikKraj { get; set; }
        public string PlatnikNip { get; set; }
        public int? KlientNadId { get; set; }
        public string KlientNadSymbol { get; set; }
        public string KlientNadNazwa { get; set; }
        public string KlientNadAdres { get; set; }
        public string KlientNadMiasto { get; set; }
        public string KlientNadKod { get; set; }
        public string KlientNadKraj { get; set; }
        public string KlientNadNip { get; set; }
        public string KlientNadTel { get; set; }
        public string KlientNadFax { get; set; }
        public string KlientNadKont { get; set; }
        public int? KlientOdbId { get; set; }
        public string KlientOdbSymbol { get; set; }
        public string KlientOdbNazwa { get; set; }
        public string KlientOdbAdres { get; set; }
        public string KlientOdbMiasto { get; set; }
        public string KlientOdbKod { get; set; }
        public string KlientOdbKraj { get; set; }
        public string KlientOdbNip { get; set; }
        public string KlientOdbTel { get; set; }
        public string KlientOdbFax { get; set; }
        public string KlientOdbKont { get; set; }
        public string MiejsceZa { get; set; }
        public int? MiejsceZaId { get; set; }
        public string MiejsceZaNazwa { get; set; }
        public string MiejsceZaAdres { get; set; }
        public string MiejsceZaMiasto { get; set; }
        public string MiejsceZaKod { get; set; }
        public string MiejsceZaKraj { get; set; }
        public string MiejsceZaTel { get; set; }
        public string MiejsceZaFax { get; set; }
        public string MiejsceZaKont { get; set; }
        public string MiejsceWy { get; set; }
        public int? MiejsceWyId { get; set; }
        public string MiejsceWyNazwa { get; set; }
        public string MiejsceWyAdres { get; set; }
        public string MiejsceWyMiasto { get; set; }
        public string MiejsceWyKod { get; set; }
        public string MiejsceWyKraj { get; set; }
        public string MiejsceWyTel { get; set; }
        public string MiejsceWyFax { get; set; }
        public string MiejsceWyKont { get; set; }
        public string MiejsceCZa { get; set; }
        public int? MiejsceCZaId { get; set; }
        public string MiejsceCZaNazwa { get; set; }
        public string MiejsceCZaAdres { get; set; }
        public string MiejsceCZaMiasto { get; set; }
        public string MiejsceCZaKod { get; set; }
        public string MiejsceCZaKraj { get; set; }
        public string MiejsceCZaTel { get; set; }
        public string MiejsceCZaFax { get; set; }
        public string MiejsceCZaKont { get; set; }
        public string MiejsceCWy { get; set; }
        public int? MiejsceCWyId { get; set; }
        public string MiejsceCWyNazwa { get; set; }
        public string MiejsceCWyAdres { get; set; }
        public string MiejsceCWyMiasto { get; set; }
        public string MiejsceCWyKod { get; set; }
        public string MiejsceCWyKraj { get; set; }
        public string MiejsceCWyTel { get; set; }
        public string MiejsceCWyFax { get; set; }
        public string MiejsceCWyKont { get; set; }
        public string StatusCelny { get; set; }
        public string WarunkiDostawy { get; set; }
        public string Kierunek { get; set; }
        public int? TrasaId { get; set; }
        public string Trasa { get; set; }
        public double? TrasaKm { get; set; }
        public string Usluga { get; set; }
        public string Uwagi { get; set; }
        public string UwagiPod { get; set; }
        public int? JestPobranie { get; set; }
        public double? KwotaPobranie { get; set; }
        public string WalutaPobranie { get; set; }
        public int? JestUbezp { get; set; }
        public double? KwotaUbezp { get; set; }
        public string WalutaUbezp { get; set; }
        public double? KwotaExw { get; set; }
        public string WalutaExw { get; set; }
        public string KontoExw { get; set; }
        public double? WartoscTowaru { get; set; }
        public string WalutaWartoscTowaru { get; set; }
        public double? OplatyCelne { get; set; }
        public string WalutaOplatyCelne { get; set; }
        public string NrDeklaracji { get; set; }
        public string OpisTowaru { get; set; }
        public string PochodzenieTowaru { get; set; }
        public string NrFaktury { get; set; }
        public DateTime? DataFaktury { get; set; }
        public double? IloscDekl { get; set; }
        public double? WagaDekl { get; set; }
        public double? ObjDekl { get; set; }
        public double? WagaRzeczywista { get; set; }
        public double? ObjRzeczywista { get; set; }
        public double? WagaKubaturowa { get; set; }
        public double? WagaLadowna { get; set; }
        public double? Dluzyca { get; set; }
        public double? WagaObl { get; set; }
        public int? Adr { get; set; }
        public int? Celna { get; set; }
        public int? Direct { get; set; }
        public int? StatusMail { get; set; }
        public string Stan { get; set; }
        public string OstStatus { get; set; }
        public int? MagazynP { get; set; }
        public int? MagazynR { get; set; }
        public int? ListLiniowyId { get; set; }
        public string ListLiniowy { get; set; }
        public int? ListLiniowyDystId { get; set; }
        public string ListLiniowyDyst { get; set; }
        public int? WyjazdId { get; set; }
        public string Wyjazd { get; set; }
        public double? ProcentKosztow { get; set; }
        public int? PartnerId { get; set; }
        public string Partner { get; set; }
        public string WalutaKalkulacji { get; set; }
        public int? TabelaKursowKalkulacjiId { get; set; }
        public string TabelaKursowKalkulacji { get; set; }
        public int? CmrId { get; set; }
        public string Cmr { get; set; }
        public DateTime? DataCmr { get; set; }
        public string Lokalizacja { get; set; }
        public string LokalizacjaPosr { get; set; }
        public int? FakturaWystawiona { get; set; }
        public int? Techniczne { get; set; }
        public string Ustalenia { get; set; }
        public string UstaleniaPotw { get; set; }
        public string InfoDlaKsieg { get; set; }
        public string Ref1 { get; set; }
        public string Ref2 { get; set; }
        public string Ref3 { get; set; }
        public int? PrzewoznikDystId { get; set; }
        public string PrzewoznikDyst { get; set; }
        public double? FrachtPrzewoznikaDyst { get; set; }
        public string NumerCfr { get; set; }
        public string Destynacja { get; set; }
        public int? Fumigacja { get; set; }
        public string Terms { get; set; }
        public string Delivery { get; set; }
        public string Vessel { get; set; }
        public string Bill { get; set; }
        public string Placeofreceipt { get; set; }
        public string Portofloading { get; set; }
        public string Portofdischarge { get; set; }
        public string Portofdelivery { get; set; }
        public DateTime? Sailed { get; set; }
        public DateTime? Expected { get; set; }
        public string Nref { get; set; }
        public string Wref { get; set; }
        public int? SamochodId { get; set; }
        public string Samochod { get; set; }
        public int? Zalaczniki { get; set; }
        /// <summary>
        /// Relacja do użytkownika tworzącego rekord - tab: UZYTKOWNIK
        /// </summary>
        public int? CreateIdUser { get; set; }
        /// <summary>
        /// Nazwa użytkownika tworzącego rekord
        /// </summary>
        public string CreateUserName { get; set; }
        /// <summary>
        /// Data utworzenia
        /// </summary>
        public DateTime? CreateDate { get; set; }
        /// <summary>
        /// Godzina utworzenia
        /// </summary>
        public DateTime? CreateTime { get; set; }
        /// <summary>
        /// Relacja do użytkownika który ostatni modyfikował rekord - tab: UZYTKOWNIK
        /// </summary>
        public int? ModifyIdUser { get; set; }
        /// <summary>
        /// Nazwa użytkownika modyfikującego rekord
        /// </summary>
        public string ModifyUserName { get; set; }
        /// <summary>
        /// Data ostatniej modyfikacji
        /// </summary>
        public DateTime? ModifyDate { get; set; }
        /// <summary>
        /// Godzina ostatniej modyfikacji
        /// </summary>
        public DateTime? ModifyTime { get; set; }
        public string Kontener { get; set; }
        public string Typ { get; set; }
        public string StrefaNad { get; set; }
        public string StrefaOdb { get; set; }
        public int? StatusWejscia { get; set; }
        public int? StatusZmiany { get; set; }
        public double? WagaWyjscia { get; set; }
        public double? ObjWyjscia { get; set; }
        public int? StatusCelnyId { get; set; }
        public int? PotwOdpr { get; set; }
        public int? ListLiniowyLp { get; set; }
        public int? ListLiniowySkan { get; set; }
        public string Przewoznik { get; set; }
        public int? ListLiniowyDystLp { get; set; }
        public int? ListLiniowyDystSkan { get; set; }
        public string SamochodDyst { get; set; }
        public int? IdMc { get; set; }
        public int? IdMcwyd { get; set; }
        public int? IdMcdwyd { get; set; }
        public int? KontenerId { get; set; }
        public string Opiekun { get; set; }
        public string TypP { get; set; }
        public string TypPojazdu { get; set; }
        public int? Rekalkulacja { get; set; }
        public string TypZlecenia { get; set; }
        public string Slot1 { get; set; }
        public string Slot2 { get; set; }
        public string Slot3 { get; set; }
        public string Slot4 { get; set; }
        public string Slot5 { get; set; }
        public int? Podprzesylka { get; set; }
        public int? NrPodprzesylki { get; set; }
        public int? MaPodprzesylki { get; set; }
        public int? PrzesylkaNadrzId { get; set; }
        public int? PodprzesylkaNadrzId { get; set; }
        public int? KalkKomasId { get; set; }
        public int? Ok { get; set; }
        public double? IloscRzeczywista { get; set; }
        public string Opakowanie { get; set; }
        public int? PonownePlanowanie { get; set; }
        public int? Podjecie { get; set; }
        public string StatusLok { get; set; }
        public string Slot1Lok { get; set; }
        public string Slot2Lok { get; set; }
        public string Slot3Lok { get; set; }
        public string Slot4Lok { get; set; }
        public string Slot5Lok { get; set; }
        public string OstStatusL { get; set; }
        public string Slot1L { get; set; }
        public string Slot2L { get; set; }
        public string Slot3L { get; set; }
        public string Slot4L { get; set; }
        public string Slot5L { get; set; }
        public string LokalizacjaNadz { get; set; }
        public int? ZwrDokLokPosr { get; set; }
        public int? DokOk { get; set; }
        public DateTime? DokOkData { get; set; }
        public int? Anomalia { get; set; }
        public string ZwrotDo { get; set; }
        public int? ZwrotDoId { get; set; }
        public int? MaZwrot { get; set; }
        public DateTime? GodzZlecenia { get; set; }
        public DateTime? DataPotwierdzenia { get; set; }
        public int? Terminowosc { get; set; }
        public int? Ekspresowa { get; set; }
        public DateTime? PlanDataZalDo { get; set; }
        public DateTime? PlanGodzZalDo { get; set; }
        public DateTime? PlanDataRozDo { get; set; }
        public DateTime? PlanGodzRozDo { get; set; }
        public int? TrafikId { get; set; }
        public string Trafik { get; set; }
        public int? JestPobranieFracht { get; set; }
        public string FormaPobranie { get; set; }
        public int? RozlPobranie { get; set; }
        public DateTime? DataRozlPobranie { get; set; }
        public int? RozlPobranieK { get; set; }
        public DateTime? DataRozlPobranieK { get; set; }
        public double? WagaDoObl { get; set; }
        public double? WagaMax { get; set; }
        public double? Ldm { get; set; }
        public int? DluzycaDod { get; set; }
        public double? DluzycaDodKg { get; set; }
        public double? MiejscaPal { get; set; }
        public int? SpWyliczWagiObl { get; set; }
        public string AdrUn { get; set; }
        public string TranzytInfo { get; set; }
        public string PonownePlanowanieLok { get; set; }
        public int? PodjeciePom { get; set; }
        public int? Podjecie1Ll { get; set; }
        public string MagGdzieJest { get; set; }
        public DateTime? MagGdzieJestDataGodz { get; set; }
        public string PartnerTrafik { get; set; }
        public string Dzial { get; set; }
        public int? DostawaMagazyn { get; set; }
        public string LokalizacjaMag { get; set; }
        public int? InstrDod { get; set; }
        public string StatusEmisja { get; set; }
        public int? SaKontakty { get; set; }
        public int? FakturaId { get; set; }
        public string Faktura { get; set; }
        public string Ref4 { get; set; }
        public string Ref5 { get; set; }
        public string RefBordero { get; set; }
        public int? Stop { get; set; }
        public string StopInfo { get; set; }
        public string TrasaKod { get; set; }
        public double? OplataPobranie { get; set; }
        public string WalutaOplataPobranie { get; set; }
        public int? OpakWym { get; set; }
        public string OpakWymOpis { get; set; }
        public double? OpakWymIlosc { get; set; }
        public int? WymianaPaletRozl { get; set; }
        public int? WymianaPaletWysl { get; set; }
        public DateTime? WymianaPaletWyslData { get; set; }
        public int? AdrWyl { get; set; }
        public string AdrWylInfo { get; set; }
        public string LokalizacjaCloWw { get; set; }
        public string LokalizacjaCloWy { get; set; }
        public string KodOpak { get; set; }
        public double? LdmDekl { get; set; }
        public string DokRozlPobranie { get; set; }
        public string DokRozlPobranieK { get; set; }
        public double? MiejscaPalDekl { get; set; }
        public DateTime? TrigTimestamp { get; set; }
        public string DzialOdp { get; set; }
        public double? DluzycaDekl { get; set; }
        public int? ListLiniowyDystrId { get; set; }
        public string ZwrotTyp { get; set; }
        public string NrZleceniaK { get; set; }
        public int? PozycjaOferty { get; set; }
        public int? OfertaId { get; set; }
        public int? OfertaPozycjaId { get; set; }
        public string Oferta { get; set; }
        public string SqlDebugInfo { get; set; }
        public int? Checklistok { get; set; }
        public int? EmiOrgId { get; set; }
        public DateTime? DataWyk { get; set; }
        public double? MiejscaPalObl { get; set; }
        public string OrgTypP { get; set; }
        public string NrPrzesylkiEx2 { get; set; }
        public string OpiekunHandl { get; set; }
        public int? StrefaNadR { get; set; }
        public int? StrefaOdbR { get; set; }
        public int? BezDystrybucji { get; set; }
        public int? RozlPobranieKierowca { get; set; }
    }
}
