using System;
using System.Collections.Generic;

namespace API.Models
{
    public partial class TmpZleceniaCyst
    {
        public int IdTmpZleceniaCyst { get; set; }
        public int? IdSesjiKalk { get; set; }
        public int? IdZlecenia { get; set; }
        public int? Komora1 { get; set; }
        public string Ladunek1 { get; set; }
        public double? Waga1 { get; set; }
        public double? WagaRz1 { get; set; }
        public string JednWagi1 { get; set; }
        public double? Obj1 { get; set; }
        public double? ObjRz1 { get; set; }
        public string Adr1 { get; set; }
        public double? Gestosc1 { get; set; }
        public double? Cisn1 { get; set; }
        public string JednCisn1 { get; set; }
        public string Temp1 { get; set; }
        public string TempRz1 { get; set; }
        public double? WagaZest1 { get; set; }
        public double? WagaBrutto1 { get; set; }
        public int? Komora2 { get; set; }
        public string Ladunek2 { get; set; }
        public double? Waga2 { get; set; }
        public double? WagaRz2 { get; set; }
        public string JednWagi2 { get; set; }
        public double? Obj2 { get; set; }
        public double? ObjRz2 { get; set; }
        public string Adr2 { get; set; }
        public double? Gestosc2 { get; set; }
        public double? Cisn2 { get; set; }
        public string JednCisn2 { get; set; }
        public string Temp2 { get; set; }
        public string TempRz2 { get; set; }
        public double? WagaZest2 { get; set; }
        public double? WagaBrutto2 { get; set; }
        public int? Komora3 { get; set; }
        public string Ladunek3 { get; set; }
        public double? Waga3 { get; set; }
        public double? WagaRz3 { get; set; }
        public string JednWagi3 { get; set; }
        public double? Obj3 { get; set; }
        public double? ObjRz3 { get; set; }
        public string Adr3 { get; set; }
        public double? Gestosc3 { get; set; }
        public double? Cisn3 { get; set; }
        public string JednCisn3 { get; set; }
        public string Temp3 { get; set; }
        public string TempRz3 { get; set; }
        public double? WagaZest3 { get; set; }
        public double? WagaBrutto3 { get; set; }
        public int? Komora4 { get; set; }
        public string Ladunek4 { get; set; }
        public double? Waga4 { get; set; }
        public double? WagaRz4 { get; set; }
        public string JednWagi4 { get; set; }
        public double? Obj4 { get; set; }
        public double? ObjRz4 { get; set; }
        public string Adr4 { get; set; }
        public double? Gestosc4 { get; set; }
        public double? Cisn4 { get; set; }
        public string JednCisn4 { get; set; }
        public string Temp4 { get; set; }
        public string TempRz4 { get; set; }
        public double? WagaZest4 { get; set; }
        public double? WagaBrutto4 { get; set; }
        public int? Komora5 { get; set; }
        public string Ladunek5 { get; set; }
        public double? Waga5 { get; set; }
        public double? WagaRz5 { get; set; }
        public string JednWagi5 { get; set; }
        public double? Obj5 { get; set; }
        public double? ObjRz5 { get; set; }
        public string Adr5 { get; set; }
        public double? Gestosc5 { get; set; }
        public double? Cisn5 { get; set; }
        public string JednCisn5 { get; set; }
        public string Temp5 { get; set; }
        public string TempRz5 { get; set; }
        public double? WagaZest5 { get; set; }
        public double? WagaBrutto5 { get; set; }
        public int? Komora6 { get; set; }
        public string Ladunek6 { get; set; }
        public double? Waga6 { get; set; }
        public double? WagaRz6 { get; set; }
        public string JednWagi6 { get; set; }
        public double? Obj6 { get; set; }
        public double? ObjRz6 { get; set; }
        public string Adr6 { get; set; }
        public double? Gestosc6 { get; set; }
        public double? Cisn6 { get; set; }
        public string JednCisn6 { get; set; }
        public string Temp6 { get; set; }
        public string TempRz6 { get; set; }
        public double? WagaZest6 { get; set; }
        public double? WagaBrutto6 { get; set; }
        public int? Komora7 { get; set; }
        public string Ladunek7 { get; set; }
        public double? Waga7 { get; set; }
        public double? WagaRz7 { get; set; }
        public string JednWagi7 { get; set; }
        public double? Obj7 { get; set; }
        public double? ObjRz7 { get; set; }
        public string Adr7 { get; set; }
        public double? Gestosc7 { get; set; }
        public double? Cisn7 { get; set; }
        public string JednCisn7 { get; set; }
        public string Temp7 { get; set; }
        public string TempRz7 { get; set; }
        public double? WagaZest7 { get; set; }
        public double? WagaBrutto7 { get; set; }
    }
}
