using System;
using System.Collections.Generic;

namespace API.Models
{
    public partial class Zlecenium
    {
        public int IdZlecenia { get; set; }
        public int? FrmId { get; set; }
        public string NrZlecenia { get; set; }
        public int? NrZlecKolejny { get; set; }
        public int? NrZlecRok { get; set; }
        public int? NrZlecMies { get; set; }
        public string NrZleceniaK { get; set; }
        public int? NrZlecKolejnyK { get; set; }
        public int? NrZlecRokK { get; set; }
        public int? NrZlecMiesK { get; set; }
        public int? TeczkaId { get; set; }
        public string Teczka { get; set; }
        public string JezykZlecenia { get; set; }
        public string Typ { get; set; }
        public int? SpedytorId { get; set; }
        public string Spedytor { get; set; }
        public DateTime? DataZlecenia { get; set; }
        public int? KlientId { get; set; }
        public string KlientSymbol { get; set; }
        public string KlientNazwa { get; set; }
        public string KlientAdres { get; set; }
        public string KlientMiasto { get; set; }
        public string KlientKod { get; set; }
        public string KlientKraj { get; set; }
        public string KlientNip { get; set; }
        public string KlientTel { get; set; }
        public string KlientKont { get; set; }
        public int? PlatnikId { get; set; }
        public string PlatnikSymbol { get; set; }
        public string PlatnikNazwa { get; set; }
        public string PlatnikAdres { get; set; }
        public string PlatnikMiasto { get; set; }
        public string PlatnikKod { get; set; }
        public string PlatnikKraj { get; set; }
        public string PlatnikNip { get; set; }
        public int? PrzewoznikId { get; set; }
        public string PrzewoznikSymbol { get; set; }
        public string PrzewoznikNazwa { get; set; }
        public string PrzewoznikAdres { get; set; }
        public string PrzewoznikMiasto { get; set; }
        public string PrzewoznikKod { get; set; }
        public string PrzewoznikKraj { get; set; }
        public string PrzewoznikNip { get; set; }
        public string PrzewoznikTel { get; set; }
        public string PrzewoznikKont { get; set; }
        public string WarunkiDostawy { get; set; }
        public string TypZlecenia { get; set; }
        public string ZaMiejsce { get; set; }
        public string ZaMiasto { get; set; }
        public string ZaKraj { get; set; }
        public DateTime? ZaData { get; set; }
        public DateTime? ZaGodz { get; set; }
        public DateTime? ZaDataRz { get; set; }
        public DateTime? ZaGodzRz { get; set; }
        public string WyMiejsce { get; set; }
        public string WyMiasto { get; set; }
        public string WyKraj { get; set; }
        public DateTime? WyData { get; set; }
        public DateTime? WyGodz { get; set; }
        public DateTime? WyDataRz { get; set; }
        public DateTime? WyGodzRz { get; set; }
        public DateTime? DataRozladFk { get; set; }
        public string ZrodDatyRozlFk { get; set; }
        public int? OdprawaCelnaWywozId { get; set; }
        public string OdprawaCelnaWywoz { get; set; }
        public int? OdprawaCelnaWwozId { get; set; }
        public string OdprawaCelnaWwoz { get; set; }
        public int? OdprawaGranicznaId { get; set; }
        public string OdprawaGraniczna { get; set; }
        public int? TrasaId { get; set; }
        public string Trasa { get; set; }
        public int? TrasaEdycja { get; set; }
        public double? TrasaOdl { get; set; }
        public double? TrasaOdlDojazd { get; set; }
        public double? TrasaOdlGl { get; set; }
        public double? TrasaZlecOdl { get; set; }
        public double? TrasaZlecOdlDojazd { get; set; }
        public double? TrasaZlecOdlGl { get; set; }
        public double? TrasaOdlRozn { get; set; }
        public string OpisTowaru { get; set; }
        public string OpisWymagTaboru { get; set; }
        public double? WartoscLadunku { get; set; }
        public string WartoscLadunkuWal { get; set; }
        public string JednWagi { get; set; }
        public double? WagaLadunku { get; set; }
        public double? ObjetoscLadunku { get; set; }
        public double? Wysokosc { get; set; }
        public double? Szerokosc { get; set; }
        public double? Dlugosc { get; set; }
        public string TypOpakowania { get; set; }
        public double? IloscOpakowan { get; set; }
        public string DodOpakowania { get; set; }
        public int? Adr { get; set; }
        public string DodJm { get; set; }
        public int? DodIl { get; set; }
        public int? KubaturaPojazdu { get; set; }
        public string InfoDod { get; set; }
        public string InfoDodKl { get; set; }
        public int? OfertaId { get; set; }
        public int? OfertaPozycjaId { get; set; }
        public string Oferta { get; set; }
        public int? WyjazdId { get; set; }
        public string Wyjazd { get; set; }
        public int? CmrId { get; set; }
        public string Cmr { get; set; }
        public DateTime? DataCmr { get; set; }
        public string Faktura { get; set; }
        public int? FakturaZbId { get; set; }
        public string FakturaZb { get; set; }
        public string FakturaK { get; set; }
        public int? FakturaKZbId { get; set; }
        public string FakturaKZb { get; set; }
        public string SamochodNrBoczny { get; set; }
        public int? SamochodId { get; set; }
        public string Samochod { get; set; }
        public int? NaczepaKlienta { get; set; }
        public string NaczepaNrBoczny { get; set; }
        public int? NaczepaId { get; set; }
        public string Naczepa { get; set; }
        public int? Kierowca1Id { get; set; }
        public string Kierowca1 { get; set; }
        public string Kierowca1Tel { get; set; }
        public int? Kierowca2Id { get; set; }
        public string Kierowca2 { get; set; }
        public string Kierowca2Tel { get; set; }
        public int? CennikFtlId { get; set; }
        public string CennikFtl { get; set; }
        public int? CennikFtlPId { get; set; }
        public string CennikFtlP { get; set; }
        public double? KwotaK { get; set; }
        public string WalutaK { get; set; }
        public string TypKursK { get; set; }
        public string FormaPlatnosciK { get; set; }
        public int? TerminK { get; set; }
        public int? OdcKrajowyKmK { get; set; }
        public double? OdcKrajowyK { get; set; }
        public double? OdcKrajowyVatK { get; set; }
        public string OdcKrajowyVatIdK { get; set; }
        public int? OdcUeKmK { get; set; }
        public double? OdcUeK { get; set; }
        public double? OdcUeVatK { get; set; }
        public string OdcUeVatIdK { get; set; }
        public int? OdcZagranicznyKmK { get; set; }
        public double? OdcZagranicznyK { get; set; }
        public double? OdcZagranicznyVatK { get; set; }
        public string OdcZagranicznyVatIdK { get; set; }
        public double? KwotaP { get; set; }
        public string WalutaP { get; set; }
        public string TypKursP { get; set; }
        public string FormaPlatnosciP { get; set; }
        public int? TerminP { get; set; }
        public int? OdcKrajowyKmP { get; set; }
        public double? OdcKrajowyP { get; set; }
        public double? OdcKrajowyVatP { get; set; }
        public string OdcKrajowyVatIdP { get; set; }
        public int? OdcUeKmP { get; set; }
        public double? OdcUeP { get; set; }
        public double? OdcUeVatP { get; set; }
        public string OdcUeVatIdP { get; set; }
        public int? OdcZagranicznyKmP { get; set; }
        public double? OdcZagranicznyP { get; set; }
        public double? OdcZagranicznyVatP { get; set; }
        public string OdcZagranicznyVatIdP { get; set; }
        public string Status { get; set; }
        public string StatusMail { get; set; }
        public string StatusEmisja { get; set; }
        public string RefNad { get; set; }
        public string RefOdb { get; set; }
        public string RefPos { get; set; }
        public int? MiesRozl { get; set; }
        public int? RokRozl { get; set; }
        public double? KwotaKUstalona { get; set; }
        public double? StawkaZaKm { get; set; }
        public int? Idctk { get; set; }
        public double? PodstProwizjiKier { get; set; }
        public int? ZlecenieId { get; set; }
        public string Zlecenie { get; set; }
        public string Podzlecenie { get; set; }
        public double? ProcentKosztow { get; set; }
        public string Lokalizacja { get; set; }
        public string Ustalenia { get; set; }
        public string UstaleniaPotw { get; set; }
        public string InfoDlaKsieg { get; set; }
        public int? Ok { get; set; }
        public double? ASumaFraPw { get; set; }
        public double? ASumaKmPw { get; set; }
        public double? AStawkaPw { get; set; }
        public double? AStawkaUstM { get; set; }
        public double? AStawkaUst { get; set; }
        public int? AStatOplac { get; set; }
        public int? SfmStatus { get; set; }
        public int? SfmVer { get; set; }
        public int? SfmLZaWy { get; set; }
        public int? SfmWysl { get; set; }
        public int? Zalaczniki { get; set; }
        /// <summary>
        /// Relacja do użytkownika tworzącego rekord - tab: UZYTKOWNIK
        /// </summary>
        public int? CreateIdUser { get; set; }
        /// <summary>
        /// Nazwa użytkownika tworzącego rekord
        /// </summary>
        public string CreateUserName { get; set; }
        /// <summary>
        /// Data utworzenia
        /// </summary>
        public DateTime? CreateDate { get; set; }
        /// <summary>
        /// Godzina utworzenia
        /// </summary>
        public DateTime? CreateTime { get; set; }
        /// <summary>
        /// Relacja do użytkownika który ostatni modyfikował rekord - tab: UZYTKOWNIK
        /// </summary>
        public int? ModifyIdUser { get; set; }
        /// <summary>
        /// Nazwa użytkownika modyfikującego rekord
        /// </summary>
        public string ModifyUserName { get; set; }
        /// <summary>
        /// Data ostatniej modyfikacji
        /// </summary>
        public DateTime? ModifyDate { get; set; }
        /// <summary>
        /// Godzina ostatniej modyfikacji
        /// </summary>
        public DateTime? ModifyTime { get; set; }
        public int? VatNaSadzie { get; set; }
        public DateTime? FakturaData { get; set; }
        public double? StawkaZaWagaKm { get; set; }
        public string Kontener { get; set; }
        public int? KontenerId { get; set; }
        public double? TempPrzewozu { get; set; }
        public string TempPrzewozuO { get; set; }
        public string LokalizacjaPosr { get; set; }
        public string Opiekun { get; set; }
        public int? RozlKier { get; set; }
        public int? RozKierAkt { get; set; }
        public double? RozKierFracht { get; set; }
        public string OpisTowaruUn { get; set; }
        public int? WymianaPalet { get; set; }
        public int? NaczepaPaletyPocz { get; set; }
        public int? NaczepaPaletyKon { get; set; }
        public int? NaczepaPaletyBilans { get; set; }
        public int? WymianaPaletRozl { get; set; }
        public string RodzZlec { get; set; }
        public int? Prom { get; set; }
        public int? TaborProfilId { get; set; }
        public string TaborProfil { get; set; }
        public int? StatusWstepne { get; set; }
        public string StatusWstepneOpis { get; set; }
        public double? KwotaPUstalona { get; set; }
        public double? StawkaZaKmP { get; set; }
        public double? StawkaZaWagaKmP { get; set; }
        public string WagonyNr { get; set; }
        public string WagonyDaty { get; set; }
        public string WagonyWagi { get; set; }
        public int? ListyLinioweId { get; set; }
        public string ListyLiniowe { get; set; }
        public string TrasaDojazdu { get; set; }
        public double? OrgFrachtP { get; set; }
        public double? DodFrachtWewn { get; set; }
        public double? LiczbaZawy { get; set; }
        public double? CenaZaMZawy { get; set; }
        public string CenaZaMZawyWal { get; set; }
        public string TrasaDolad { get; set; }
        public int? WymianaPaletWysl { get; set; }
        public DateTime? WymianaPaletWyslData { get; set; }
        public int? Myjnia { get; set; }
        public short? BezSfm { get; set; }
        public int? TrafikId { get; set; }
        public string Trafik { get; set; }
        public DateTime? DataPotwierdzenia { get; set; }
        public int? OddzialId { get; set; }
        public string OddzialNazwa { get; set; }
        public string OddzialAdres { get; set; }
        public string OddzialMiasto { get; set; }
        public string OddzialKod { get; set; }
        public string OddzialKraj { get; set; }
        public string ZaKod { get; set; }
        public DateTime? ZaGodzOd { get; set; }
        public DateTime? ZaGodzDo { get; set; }
        public string WyKod { get; set; }
        public DateTime? WyGodzOd { get; set; }
        public DateTime? WyGodzDo { get; set; }
        public string OpisTowaruHaccp { get; set; }
        public string OpisTowaruSqas { get; set; }
        public int? CysternaDoPelna { get; set; }
        public int? StatusKoszty { get; set; }
        public string Ref4 { get; set; }
        public string Ref5 { get; set; }
        public int? Przeladunek { get; set; }
        public string Dzial { get; set; }
        public int? SaKontakty { get; set; }
        public string NrBl { get; set; }
        public string NrBlOdb { get; set; }
        public int? NrBlOdbId { get; set; }
        public string NrBlArm { get; set; }
        public int? NrBlArmId { get; set; }
        public string NrAwb { get; set; }
        public string NrAwbOdb { get; set; }
        public int? NrAwbOdbId { get; set; }
        public string NrAwbLot { get; set; }
        public int? NrAwbLotId { get; set; }
        public int? DokOk { get; set; }
        public DateTime? DokOkData { get; set; }
        public int? JestRw { get; set; }
        public int? DyspozytorId { get; set; }
        public string Dyspozytor { get; set; }
        public DateTime? WyDataRzK { get; set; }
        public DateTime? WyGodzRzK { get; set; }
        public double? WagaLadunkuRz { get; set; }
        public string FakturaPf { get; set; }
        public int? TypTabK { get; set; }
        public int? TypTabP { get; set; }
        public DateTime? GodzZlecenia { get; set; }
        public string WalutaFvK { get; set; }
        public string WalutaFvP { get; set; }
        public DateTime? ZaDataDok { get; set; }
        public DateTime? WyDataDok { get; set; }
        public int? Tranzyt { get; set; }
        public double? TrasaMapOdl { get; set; }
        public double? TrasaMapOdlDojazd { get; set; }
        public double? TrasaMapOdlGl { get; set; }
        public int? Zafakturowane { get; set; }
        public int? Clenie { get; set; }
        public int? StatusCelnyId { get; set; }
        public DateTime? TrigTimestamp { get; set; }
        public int? StatusKalk { get; set; }
        public string LokalizacjaNadz { get; set; }
        public int? SpedytorAsId { get; set; }
        public string SpedytorAs { get; set; }
        public string KursWgK { get; set; }
        public int? KursZDniaPK { get; set; }
        public string KursWgP { get; set; }
        public int? KursZDniaPP { get; set; }
        public string Slot1 { get; set; }
        public string Slot2 { get; set; }
        public string Slot3 { get; set; }
        public string Slot4 { get; set; }
        public string Slot5 { get; set; }
        public int? PozycjaOferty { get; set; }
        public double? TrasaMapMyto { get; set; }
        public double? TrasaMapKmPlatne { get; set; }
        public DateTime? PcaDt { get; set; }
        public DateTime? PcaDtRz { get; set; }
        public int? VatWPlnK { get; set; }
        public int? VatWPlnP { get; set; }
        public int? Zagrozenie { get; set; }
        public int? EmiOrgId { get; set; }
        public int? AsystaPkt { get; set; }
        public int? AsystaUzytkownikId { get; set; }
        /// <summary>
        /// status wysyłki do mSPEED (10-do wysyłki / 20-odebrano)
        /// </summary>
        public int? Mobilestatus { get; set; }
        public int? Mobilesequence { get; set; }
        public DateTime? DataWyk { get; set; }
        public int? JestUbezp { get; set; }
        public int? TypUbezp { get; set; }
        public string PrzewoznikEmail { get; set; }
        public int? WwozAgencjaId { get; set; }
        public int? WywozAgencjaId { get; set; }
        public int? PotwOdpr { get; set; }
        public string Kierowca1Do { get; set; }
        public string Kierowca2Do { get; set; }
        public double? TrasaCcOdl { get; set; }
        public double? TrasaCcOdlDojazd { get; set; }
        public double? TrasaCcOdlGl { get; set; }
        public int? Anulowane { get; set; }
        public string TrybPracyAgregatu { get; set; }
        public DateTime? DataKontrWykazWl { get; set; }
        public int? WynikKontrWykazWl { get; set; }
        public string RequestId { get; set; }
        public int? SolverTaskId { get; set; }
        public int? UsrFldXserver { get; set; }
        public double? MaszKwotaK { get; set; }
        public double? UbezpProcStawka { get; set; }
        public double? UbezpProc { get; set; }
        public double? UbezpWartosc { get; set; }
    }
}
